### PR TITLE
adding bmin and bmax

### PR DESCRIPTION
**Pull request by nneveu**
Re-ran yaml generation script to include bmin and bmax in most magnet yaml files. Screens are still missing some data in a few areas. 

#103

### CODE REVIEW

**Comment by nneveu** [comment]
I needed to add the new properties in the magnet class/PV list as well.

**Comment by nneveu** [comment]
Not sure why this started failing on the fit test. Looking into it.

**Comment by nneveu** [comment]
Output of fit test `tests/unit_tests/lcls_tools/common/data_analysis/test_fit_gauss.py` seems to vary with # of runs. I'm looking into adjusting this test to be more consistent.

Output from running the test several times back to back: 

> (tools) PC101046:lcls-tools nneveu$ python -m unittest tests/unit_tests/lcls_tools/common/data_analysis/test_fit_gauss.py 
..failed returning param guesses:  [4.176414857839097, 205, 100.0, 1.3921382859463656, 102.5, 50.0, 0.9064490469346526]
.
----------------------------------------------------------------------
Ran 3 tests in 0.417s

OK
> (tools) PC101046:lcls-tools nneveu$ python -m unittest tests/unit_tests/lcls_tools/common/data_analysis/test_fit_gauss.py 
./Users/nneveu/github/lcls-tools/lcls_tools/common/data_analysis/fitting_tool.py:214: RuntimeWarning: invalid value encountered in scalar power
  return amp * np.exp((-abs(x - mu) ** (P)) / (2 * sig ** (P))) + offset
..
----------------------------------------------------------------------
Ran 3 tests in 0.048s

OK
> (tools) PC101046:lcls-tools nneveu$ python -m unittest tests/unit_tests/lcls_tools/common/data_analysis/test_fit_gauss.py 
...
----------------------------------------------------------------------
Ran 3 tests in 0.024s

OK
> (tools) PC101046:lcls-tools nneveu$ python -m unittest tests/unit_tests/lcls_tools/common/data_analysis/test_fit_gauss.py 
/Users/nneveu/miniconda3/envs/tools/lib/python3.11/site-packages/scipy/optimize/_minpack_py.py:1010: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
...
----------------------------------------------------------------------
Ran 3 tests in 0.014s

OK
> (tools) PC101046:lcls-tools nneveu$ python -m unittest tests/unit_tests/lcls_tools/common/data_analysis/test_fit_gauss.py 
.F.
======================================================================
FAIL: test_fit_tool_gaussian (tests.unit_tests.lcls_tools.common.data_analysis.test_fit_gauss.TestFitTool.test_fit_tool_gaussian)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nneveu/github/lcls-tools/tests/unit_tests/lcls_tools/common/data_analysis/test_fit_gauss.py", line 37, in test_fit_tool_gaussian
    self.assertLessEqual(val["rmse"], 0.4)
AssertionError: 0.8434927791146087 not less than or equal to 0.4

----------------------------------------------------------------------
Ran 3 tests in 0.016s

FAILED (failures=1)

**Comment by nneveu** [comment]
Opened new issue #130 to address the problem. Will skip the tests then merge this code if all other tests pass.

**Comment by nneveu** [comment]
This PR is passing relevant tests now and is ready for review.

**Comment by MattKing06** [comment]
I couldn't access EPICS as I'm not on SLAC network but the unit test cases pass, so the attribute exists at least. 

I can see the docstring says that bmin/bmax could be in `kG` or `kGm^-1`, I was wondering if adding a `b_units` property that was dependent on magnet type (which has been added) could be useful? Probably for another issue.

other than that I'm happy to merge as there is a separate issue opened for dealing with the skipped test cases.

**Review by lisazacarias — APPROVED** [review]
Looks good to me, but I'll admit that I skimmed the yaml files lol

**Pull request merged**
